### PR TITLE
Louis: Sass branch 

### PR DESCRIPTION
**Pull request by LouiaR**
I added some <p> and a <ul> list and styled with sass (loop , condition, composabilty, nesting...)

### CODE REVIEW

**Review by 40thieves — COMMENTED** [review]
Looks great 🙂 🎉

**Comment by 40thieves** [comment]
Just 1 thing - could you make sure that you keep 1 week's exercises in the same PR, just so that it's easier to keep track of everyone. If you make more commits on the branch and push again, it will update the PR with the new code

**Comment by LouiaR** [comment]
Thank you Ali for your support,  I will. I was experimenting branches. :)

**Comment by 40thieves** [comment]
No problem 🙂

**Pull request closed without merging**
